// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingDailyTracker.Data;

#nullable disable

namespace TrainingDailyTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260105211747_AddWeeklyScheduleTables")]
    partial class AddWeeklyScheduleTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TrainingDailyTracker.Entities.DailySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeeklyScheduleId");

                    b.ToTable("DailySchedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = "Lunes",
                            MuscleIds = "1",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "5",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = "Jueves",
                            MuscleIds = "3,4",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = "Viernes",
                            MuscleIds = "6",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = "Domingo",
                            MuscleIds = "7",
                            WeeklyScheduleId = 1
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = "Lunes",
                            MuscleIds = "6",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "1",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = "Jueves",
                            MuscleIds = "5,3",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = "Viernes",
                            MuscleIds = "4",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = "Domingo",
                            MuscleIds = "8",
                            WeeklyScheduleId = 2
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = "Lunes",
                            MuscleIds = "4",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "6",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = "Jueves",
                            MuscleIds = "1,5",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = "Viernes",
                            MuscleIds = "3",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = "Domingo",
                            MuscleIds = "7",
                            WeeklyScheduleId = 3
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = "Lunes",
                            MuscleIds = "3",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "4",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = "Jueves",
                            MuscleIds = "6,1",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = "Viernes",
                            MuscleIds = "5",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = "Domingo",
                            MuscleIds = "8",
                            WeeklyScheduleId = 4
                        },
                        new
                        {
                            Id = 29,
                            DayOfWeek = "Lunes",
                            MuscleIds = "5",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 30,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 31,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "3",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 32,
                            DayOfWeek = "Jueves",
                            MuscleIds = "4,6",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 33,
                            DayOfWeek = "Viernes",
                            MuscleIds = "1",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 34,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 35,
                            DayOfWeek = "Domingo",
                            MuscleIds = "7",
                            WeeklyScheduleId = 5
                        },
                        new
                        {
                            Id = 36,
                            DayOfWeek = "Lunes",
                            MuscleIds = "1",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 37,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 38,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "5",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 39,
                            DayOfWeek = "Jueves",
                            MuscleIds = "3,4",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 40,
                            DayOfWeek = "Viernes",
                            MuscleIds = "6",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 41,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 42,
                            DayOfWeek = "Domingo",
                            MuscleIds = "8",
                            WeeklyScheduleId = 6
                        },
                        new
                        {
                            Id = 43,
                            DayOfWeek = "Lunes",
                            MuscleIds = "6",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 44,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 45,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "1",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 46,
                            DayOfWeek = "Jueves",
                            MuscleIds = "5,3",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 47,
                            DayOfWeek = "Viernes",
                            MuscleIds = "4",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 48,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 49,
                            DayOfWeek = "Domingo",
                            MuscleIds = "7",
                            WeeklyScheduleId = 7
                        },
                        new
                        {
                            Id = 50,
                            DayOfWeek = "Lunes",
                            MuscleIds = "4",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 51,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 52,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "6",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 53,
                            DayOfWeek = "Jueves",
                            MuscleIds = "1,5",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 54,
                            DayOfWeek = "Viernes",
                            MuscleIds = "3",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 55,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 56,
                            DayOfWeek = "Domingo",
                            MuscleIds = "8",
                            WeeklyScheduleId = 8
                        },
                        new
                        {
                            Id = 57,
                            DayOfWeek = "Lunes",
                            MuscleIds = "3",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 58,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 59,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "4",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 60,
                            DayOfWeek = "Jueves",
                            MuscleIds = "6,1",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 61,
                            DayOfWeek = "Viernes",
                            MuscleIds = "5",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 62,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 63,
                            DayOfWeek = "Domingo",
                            MuscleIds = "7",
                            WeeklyScheduleId = 9
                        },
                        new
                        {
                            Id = 64,
                            DayOfWeek = "Lunes",
                            MuscleIds = "5",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 65,
                            DayOfWeek = "Martes",
                            MuscleIds = "2",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 66,
                            DayOfWeek = "Miércoles",
                            MuscleIds = "3",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 67,
                            DayOfWeek = "Jueves",
                            MuscleIds = "4,6",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 68,
                            DayOfWeek = "Viernes",
                            MuscleIds = "1",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 69,
                            DayOfWeek = "Sábado",
                            MuscleIds = "2",
                            WeeklyScheduleId = 10
                        },
                        new
                        {
                            Id = 70,
                            DayOfWeek = "Domingo",
                            MuscleIds = "8",
                            WeeklyScheduleId = 10
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxReps = 10,
                            MuscleId = 1,
                            Name = "Press Banca",
                            Weight = 80
                        },
                        new
                        {
                            Id = 2,
                            MaxReps = 11,
                            MuscleId = 2,
                            Name = "Sentadilla",
                            Weight = 80
                        },
                        new
                        {
                            Id = 3,
                            MaxReps = 12,
                            MuscleId = 3,
                            Name = "Press Militar",
                            Weight = 30
                        },
                        new
                        {
                            Id = 4,
                            MaxReps = 21,
                            MuscleId = 4,
                            Name = "21",
                            Weight = 30
                        },
                        new
                        {
                            Id = 5,
                            MaxReps = 10,
                            MuscleId = 5,
                            Name = "Dominadas",
                            Weight = 20
                        },
                        new
                        {
                            Id = 6,
                            MaxReps = 8,
                            MuscleId = 6,
                            Name = "Fondos",
                            Weight = 20
                        },
                        new
                        {
                            Id = 7,
                            MaxReps = 10,
                            MuscleId = 7,
                            Name = "Crunch polea",
                            Weight = 90
                        },
                        new
                        {
                            Id = 8,
                            MaxReps = 10,
                            MuscleId = 8,
                            Name = "Encogimientos",
                            Weight = 50
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "me",
                            Password = "1234 (this would be diff in production",
                            Username = "admin(this would be diff in production)"
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.WeeklyCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeeklyCycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WeekNumber = 1
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.WeeklySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeeklySchedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WeekNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            WeekNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            WeekNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            WeekNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            WeekNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            WeekNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            WeekNumber = 7
                        },
                        new
                        {
                            Id = 8,
                            WeekNumber = 8
                        },
                        new
                        {
                            Id = 9,
                            WeekNumber = 9
                        },
                        new
                        {
                            Id = 10,
                            WeekNumber = 10
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.DailySchedule", b =>
                {
                    b.HasOne("TrainingDailyTracker.Entities.WeeklySchedule", "WeeklySchedule")
                        .WithMany("DailySchedules")
                        .HasForeignKey("WeeklyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.WeeklySchedule", b =>
                {
                    b.Navigation("DailySchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
