// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingDailyTracker.Data;

#nullable disable

namespace TrainingDailyTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("TrainingDailyTracker.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exercise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxReps = 10,
                            MuscleId = 1,
                            Name = "Press Banca",
                            Weight = 80
                        },
                        new
                        {
                            Id = 2,
                            MaxReps = 11,
                            MuscleId = 2,
                            Name = "Sentadilla",
                            Weight = 80
                        },
                        new
                        {
                            Id = 3,
                            MaxReps = 12,
                            MuscleId = 3,
                            Name = "Press Militar",
                            Weight = 30
                        },
                        new
                        {
                            Id = 4,
                            MaxReps = 21,
                            MuscleId = 4,
                            Name = "21",
                            Weight = 30
                        },
                        new
                        {
                            Id = 5,
                            MaxReps = 10,
                            MuscleId = 5,
                            Name = "Dominadas",
                            Weight = 20
                        },
                        new
                        {
                            Id = 6,
                            MaxReps = 8,
                            MuscleId = 6,
                            Name = "Fondos",
                            Weight = 20
                        },
                        new
                        {
                            Id = 7,
                            MaxReps = 10,
                            MuscleId = 7,
                            Name = "Crunch polea",
                            Weight = 90
                        },
                        new
                        {
                            Id = 8,
                            MaxReps = 10,
                            MuscleId = 8,
                            Name = "Encogimientos",
                            Weight = 50
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "me",
                            Password = "1234 (this would be diff in production",
                            Username = "admin(this would be diff in production)"
                        });
                });

            modelBuilder.Entity("TrainingDailyTracker.Entities.WeeklyCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeeklyCycle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WeekNumber = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
